Fg4 35
CampusDual/BFS-2022-G1 pull request #10
Opened 2022-07-27 12:53 UTC by javierfandino

2022-07-27 12:55 UTC, cardizaDEV commented on ritapop-frontend/src/app/app.component.scss
> +/* You can add app styles to this file */
?

2022-07-27 12:55 UTC, cardizaDEV commented on ritapop-frontend/src/app/main/main.component.scss
> -}
?

2022-07-27 12:56 UTC, cardizaDEV commented on ritapop-frontend/src/app/main/clients/clients-home/clients-vip-render/clients-vip-render.component.html
> +
?

2022-07-27 12:59 UTC, cardizaDEV approved these changes

2022-07-27 13:29 UTC, DonatoRM requested changes
La inserción de transacciones funciona mal.
Los datos que he introducido para la comprobación son los siguientes:

- Nombre producto: Lavadora
- Categoría producto: hogar
- Nif vender: 27610483H
- Nif comprador: 16213957S
- Fecha de pago: 28/07/2022
- Fecha de entrega: 30/07/2022
- Mñetodo de pago: Tarjeta
- Precio: 550

Provar, pero no inserta los datos, ya que da un error.

El ID_TRANSACTIONS de la tabla de transacciones sigue sin cambiarse al idioma correcto.
¿Puede haber una fecha de pago antes que la fecha de entre y viceversa? No lo sé. Debemos de hablarlo.
Por favor, corregir problemas.

2022-07-27 21:43 UTC, tomascarralero requested changes
Tras realizar la pruebas creo que habría que revisar los siguientes puntos para hacer algunos cambios:

1) La inserción falla si los DNIs introducidos no existen previamente en la tabla de CLIENT, habría que pensar cómo podemos resolverlo (quizás exista una forma de sacar un modal en Ontimize con la lista de clientes para poder seleccionar uno o crearlo).

2) Completar las traducciones de ID_TRANSACTION.

3) Valorar si podemos controlar que la fecha de entrega no sea anterior a la fecha de pago.

4) Valorar el añadir en el fichero `styles.css` que está en la carpeta **src** la siguiente declaración para separar mejor los inputs del formulario del detalle:
`.input-padding{
    padding-right: 6px;
  }`

2022-07-27 21:43 UTC, tomascarralero commented on ritapop-frontend/src/assets/i18n/en.json
>  }
Habría que añadir la traducción para ID_TRANSACTIONS al inglés.

2022-07-27 21:43 UTC, tomascarralero commented on ritapop-frontend/src/assets/i18n/es.json
>  }
Habría que añadir la traducción para ID_TRANSACTIONS al castellano.

2022-07-28 08:52 UTC, Cinta-tafur approved these changes

2022-07-28 08:55 UTC, DonatoRM approved these changes

2022-07-28 08:55 UTC, merged